### ISSUE TITLE
Phalcon 3 & 4 support

### ISSUE THREAD

**Issue by ekoeryanto** [phalcon/bridge-swoole#7]
Hello, just see the composer.json it implicit to phalcon 5 and php 8, can we support phalcon 3 & 4 also php >=7?

**Comment by Jeckerson** [comment]
Unfortunately no. Due legacy code of Zephir and a lot of its changes it is near impossible to build it nowadays. Also there were a lot of memory leak fixes in Phalcon v5 which is much more stable with Swoole. Here is the blog post about my journey of memory management - https://blog.phalcon.io/post/high-load-micro-service

If you need any help you migrate your apps into latest PHP and Phalcon versions, feel free to join our [discord server](https://phalcon.io/discord) and ask for any help.
